### ISSUE TITLE
Crash when resetting a lowshelf filter's dbgain

### ISSUE THREAD

**Issue by ctoth** [camlorn/libaudioverse#2]
If you first create a lowshelf filter, get it working on some audio, then change its dbgain, the entire app freezes and breaks.
Here is a test which reproduces this behavior:
```python
import os
print os.getpid()
import libaudioverse
libaudioverse.initialize()
sim = libaudioverse.Simulation()
world = libaudioverse.EnvironmentNode(sim, "default")
world.default_panning_strategy =libaudioverse.PanningStrategies.hrtf
world.default_max_distance = 20
world.default_distance_model = libaudioverse.DistanceModels.exponential
world.output_channels.value= 2
world.connect_simulation(0)
sim.set_output_device(-1)
source = libaudioverse.SourceNode(sim, world)
filter = libaudioverse.BiquadNode(sim, 2)
filter.filter_type = 5
filter.dbgain = -10
filter.connect(0, source, 0)
sound_buffer = libaudioverse.Buffer(sim)
sound_buffer.load_from_file('sounds/ambience.ogg')

sound = libaudioverse.BufferNode(sim)
sound.buffer = sound_buffer
sound.connect(0, filter, 0)
sound.looping=True

filter.dbgain = -20
```

**Comment by camlorn** [comment]
This isn't crashing for me, and I was never able to duplicate it.  Is it still crashing for you?
I think this was possibly related to another bug in [audio_io](http://github.com/camlorn/audio_io.git), but that was brought to my attention outside of the Github issue tracker and never got a ticket.

**Comment by camlorn** [comment]
This appears to have fixed itself somewhere else.  I'm closing it.  If this is still a bug, it's a rare set of circumstances that triggers it.
