### ISSUE TITLE
CSS file missing in Python online docs

### ISSUE THREAD

**Issue by mgeier** [camlorn/libaudioverse#29]
The page http://camlorn.github.io/libaudioverse/docs/branches/master/python/ (which is mentioned in the README file) tries to load the CSS file `_static/css/theme.css`, which doesn't seem to exist on the server.

When I build the docs locally, everything is fine.

**Comment by camlorn** [comment]
This is probably something to do with Appveyor configuration, maybe a missing Sphinx theme or somesuch.

I'm actually blind.  What problem is this causing?  I hadn't noticed that this was happening.  Are the docs readable, or a visual train wreck?

If this is the kind of thing which can be left for a time, my goal is to get off continuous integration for the release process as it's ended up being more trouble than it's worth.  I'd like to fix it then.

can you tell if any other files are missing?

**Comment by mgeier** [comment]
The docs are readable, just without any CSS styling. The theme itself seems to be working OK, only some files are missing on the server:

```
_static/css/theme.css
_static/js/modernizr.min.js
_sources/index.txt
_static/jquery.js
_static/underscore.js
_static/doctools.js
_static/js/theme.js
```

Do you have a build log?

**Comment by camlorn** [comment]
Yeah, there's a build log.  But sadly not a detailed enough one to diagnose this directly.

This should nevertheless be a somewhat easy fix, so I'll take a look at it tomorrow.  If it's not, it'll really need to wait until i rewrite the bindings generation scripts.  A single test against the process we have now takes up to 20 minutes, depending how Appveyor queues it.  Every time I touch the CI stuff, it turns into a day-long project.

Sorry I didn't get around to this faster.  I've been focusing on some other work for the Rust compiler recently.

**Comment by camlorn** [comment]
I just looked at it, and those files are certainly present on the gh-pages branch and in the right places. [here](https://github.com/camlorn/libaudioverse/blob/gh-pages/docs/branches/master/python/_static/css/theme.css).

The interesting thing here is that we can't access them by URL; trying to go to `http://camlorn.github.io/libaudioverse/docs/branches/master/python/_static/css/theme.css` is a 404.

I have no idea why.

**Comment by camlorn** [comment]
This should be fixed now. Can you confirm?

By default Jekyll doesn't include fields beginning with `_`. You have to add a `.nojekyll` file to the root of the repo to fix it.

**Comment by mgeier** [comment]
Yes, now it works!
