### ISSUE TITLE
Inverted Logging Priorities

### ISSUE THREAD

**Issue by ctoth** [camlorn/libaudioverse#3]
The standard practice when logging is to have the log level represent the priority of the message, with higher levels mapping on to higher priority messages.

The default hierarchy is:
- DEBUG: 10
- INFO: 20
- WARN: 30
- ERROR: 40
- Critical: 50

LAV logging levels should be inverted to match the standard hierarchy.

**Comment by camlorn** [comment]
We only have critical, info and debug.  I've renumbered these to be in ascending order by priority and with room to add more levels in between.
